
boot:
  auth:
    enable: true
    token-expire: 30000
    refresh-expire: 300000
    token-header: Auth
    secret: user-service
    token-start-with: Bearer
  security:
    enable: false
  cors:
    enable: true

logging:
  level:
    root: info